In [17]:
import numpy as np
import pandas as pd

## **Motivation:**
- ML models work with numerical features
- Categorical features must be converted to numerical features
- Categorical features are of two types:
    - **Ordinal:**
      Some natural order, e.g., ['Small', 'Medium', 'Large']
    - **Nominal:**
      No inherent order, e.g., ['Cat', 'Dog', 'Donkey']
- Cardinality of a categorical feature equals the number of unique values assumed by it

In [18]:
n_samples = 10
ordinal_categories = ['SMALL', 'MEDIUM', 'LARGE']

data = pd.DataFrame({
    'X' : np.random.choice(ordinal_categories, size=n_samples),
})

data.head()

        X
0   LARGE
1   SMALL
2   SMALL
3   SMALL
4  MEDIUM

### **Label Encoder:**
- Assigns an integer to each category
- Introduces artificial ordering
- Good for tree-based models
- Not suitable for gradient-based / distance-based models

In [19]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
data_LE = data.copy()
data_LE['Labels'] = encoder.fit_transform(data_LE['X'].values)
data_LE.head()

        X  Labels
0   LARGE       0
1   SMALL       2
2   SMALL       2
3   SMALL       2
4  MEDIUM       1

### **Ordinal Encoding:**
- Good for ordinal features
- Assigns a number according to predefined order
- Magnitude differences are linear

In [20]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['SMALL', 'MEDIUM', 'LARGE']])
data_OE = data.copy()
data_OE['Labels'] = encoder.fit_transform(data_OE['X'].values.reshape(-1, 1))
data_OE.head()

        X  Labels
0   LARGE     2.0
1   SMALL     0.0
2   SMALL     0.0
3   SMALL     0.0
4  MEDIUM     1.0

### **One-Hot Encoder:**
- Creates an indicator variable for each unique category
- For cardinality $k$ feature, $k$ columns required
- Does not assume any order
- Suitable for gradient-based / distance-based models
- Bad for high cardinality features

In [21]:
from sklearn.preprocessing import OneHotEncoder

data_OHE = data.copy()
encoder = OneHotEncoder(sparse_output=False)
encoder.set_output(transform="pandas")
OHE_features = encoder.fit_transform(data_OHE['X'].values.reshape(-1, 1))
data_OHE = pd.concat([data_OHE, OHE_features], axis=1)
data_OHE.head()

        X  x0_LARGE  x0_MEDIUM  x0_SMALL
0   LARGE       1.0        0.0       0.0
1   SMALL       0.0        0.0       1.0
2   SMALL       0.0        0.0       1.0
3   SMALL       0.0        0.0       1.0
4  MEDIUM       0.0        1.0       0.0

**Dummy Encoding:**\
Observe that sum of all columns. For a cardinality $k$ feature,
$$ x_1 + x_2 + \cdots + x_k = 1$$
So, we can drop the last feature $x_k$ as its value is completely decided by the first $k-1$ features.

### **Binary Encoder:**
- Three step encoding,
    1. Convert feature to integers
    2. Convert integers to binary
    3. Split binary into columns
- For cardinality $k$ feature, $\lceil log(k) \rceil$ columns required
- Much lower dimensionality as compared to OHE
- Some ordering leakage remains

In [24]:
from category_encoders import BinaryEncoder

encoder = BinaryEncoder(cols=['X'])
BE_features = encoder.fit_transform(data).values
data_BE = pd.concat([data, pd.DataFrame(BE_features, columns=encoder.get_feature_names_out())], axis=1)
data_BE.head()

        X  X_0  X_1
0   LARGE    0    1
1   SMALL    1    0
2   SMALL    1    0
3   SMALL    1    0
4  MEDIUM    1    1